zooniverse/pfe-lab

src/modules/common/actions/login.js
src/modules/common/actions/organizations.js
src/modules/common/containers/header-auth.jsx

The action creators we were using in login.js and organizations.js worked but were overly complex. Also, they didn't work with the mock-redux-store testing framework. I've simplified them, which will help us either way, and I'm hoping that the simplified actions will work better with the framework.

simplify action creators

---

server.js
src/constants/config.js
src/index.jsx

This updates:
- the port to `3737` to differentiate it from the starter app.
- the client id to use a specific door keeper app in staging. 
- a router onUpdate handler to put the page back to the top. We should be using `react-router-scroll` middleware but it has a peer dep on history v3 and we're using history v4 (Updating this could be a cool open source contrib if anyone fancies that), but this should work in the meantime.

Oauth and router updates

---

.eslintrc
src/modules/common/components/landing.jsx
src/modules/common/components/site-footer.jsx
src/modules/common/components/site-nav.jsx
src/modules/common/containers/form-container.jsx
src/modules/organizations/components/edit-collaborators.jsx
src/modules/organizations/containers/collaborator-creator-container.jsx
src/modules/organizations/containers/collaborators-container.jsx
src/styles/global/form.styl
src/styles/main.styl
test/modules/common/form-container-test.js
test/modules/organizations/collaborator-creator-test.js

Still more work to do, just opening so you all can see what I've been doing.
- Adds a collaborator creator container component that tracks some local state related to the form. Also wanted to use refs. `bindInput` and adding constant variables for fields as is being done in the edit-details component just felt like a round about way of tracking state w/o the react lifecycle of the component class. 
- Enhancements for the `FormContainer`.
- Updates webpack to support vanilla css files

Collaborator creator

---

package.json
src/modules/organizations/containers/details-form-container.jsx
src/styles/global/markdown-editor.styl
yarn.lock

This is gonna need another refactor pass and I left several TODO comments for that. Otherwise, this is just adding the latest version of markdownz and the introduction field to the details editor. This should merge before the about pages.

Update markdownz and add to details editor

---

package.json
src/constants/config.js
yarn.lock

For #9 and #8, adds environments to manage the oauth app id, adds publisssh, and a npm script to run a staging deployment.

Node env for staging deploy and oauth

---

src/styles/components/organizations-list.styl

Fixes part of #69.
Currently does not crop image, so if user chooses a rectangular image, it gets distorted - moving on to other styling issues, but happy to circle back to this if we want to crop the avatar image so that rectangular images do not get distorted.

Make org-list avatars square

---

src/modules/organizations/components/organizations-list.jsx

Fixes part of #69.
Currently these links lead to the root path - not sure whether any of them should lead to project pages (eg, `project-builder-policies`), or if we will be creating our own versions of these pages for organizations.
Happy to get started on any of these static pages, if they need to get built.

Add Glossary, Policies, Best Practices, and Talk buttons to org list

---

package.json

- custom port for dashboard plugin matches the one set in [`webpack config`](https://github.com/zooniverse/pfe-lab/blob/master/webpack.config.js#L35)

Add dashboard plugin custom port to cli script.

---

Dockerfile
docker-compose.yml
package.json
src/styles/main.styl

This will be required for #9, to automate deploys with Jenkins.
Changes Zooniverse-React-Components to use https URI, because using git+ssh would require additional dependencies to be installed.
You should be able to test this with something like the following:
```
docker run -it --rm zooniverse/pfe-lab npm run-script build
```
When I try to do `npm build` here (either in Docker or natively) I get a few `Module not found` errors, which are stopping me from fully testing this myself at the moment, so it'd be good if someone else can test this too.

Add Dockerfile

---

package-lock.json
package.json
src/modules/common/components/markdown-editor.jsx
src/modules/organizations/components/about-page.jsx
src/modules/organizations/containers/details-form-container.jsx

- Resolves [Issues 87](https://github.com/zooniverse/pfe-lab/issues/87) and [88](https://github.com/zooniverse/pfe-lab/issues/88)
- Updates Markdownz dependency to 7.3.0
- Creates a common MarkdownEditor component that can be imported throughout PFE-lab
- MarkdownHelp modal (displayed via Grommet Layer) is toggled via click handler
- Updates DetailsFormContainer and AboutPage to display common MarkdownEditor and Help
See [Markdownz Issue 57](https://github.com/zooniverse/markdownz/issues/57) for related work.
- `defaultProps` in MarkdownEditor is currently defining `title` and `talk` with the same values that are given as defaultProps in the Markdownz repo. This duplication feels problematic, but @mcbouslog and I talked it over and decided to open the PR as is - suggestions for improving …

Add MarkdownHelp

---

src/modules/organizations/components/edit-details.jsx
src/modules/organizations/containers/details-form-container.jsx

- Updates instructions on the `Edit Organization Details` page. Specifically:
- Organization Description updated to indicate where it is displayed on page (below org name).
- Organization Status given explanatory text.
- Towards #109.
- Staged [here](https://update-org-details-instructions.lab-preview.zooniverse.org/organizations/14).

Update organization-details instructions

---

package.json
src/modules/common/containers/App.jsx
src/modules/common/containers/admin-container.jsx
src/modules/common/containers/bind-input.jsx
src/modules/common/containers/form-container.jsx
src/modules/common/containers/header-auth.jsx
src/modules/common/containers/image-selector.jsx

- Install `prop-types` package (~15.5.10) to avoid [deprecation warnings](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) included in React 15.5.
- Update prop types in `common/containers` to use `prop-types` package.
- Conversion to `prop-types` package will be done incrementally, to lessen the potential for merge conflicts with other outstanding PRs.
- Towards #102.

Prop types update

---

src/modules/common/components/char-limit.jsx
src/modules/common/components/landing.jsx
src/modules/common/components/layout.jsx
src/modules/common/components/login-button.jsx
src/modules/common/components/logout-button.jsx
src/modules/common/components/markdown-editor.jsx
src/modules/common/components/project-search.jsx

- Update prop types in `common/components` to use `prop-types` package to avoid [deprecation warnings](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) included in React 15.5.
- Conversion to `prop-types` package will be done incrementally, to lessen the potential for merge conflicts with other outstanding PRs.
- Towards #102.

Prop types update - common/components

---

src/modules/organizations/containers/about-container.jsx
src/modules/organizations/containers/collaborator-creator-container.jsx
src/modules/organizations/containers/collaborators-container.jsx
src/modules/organizations/containers/details-form-container.jsx
src/modules/organizations/containers/edit-details-container.jsx
src/modules/organizations/containers/organization-container.jsx
src/modules/organizations/containers/organizations-list-container.jsx
src/modules/organizations/model.js

- Update prop types in `organizations/containers` files to use `prop-types` package to avoid [deprecation warnings](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) included in React 15.5.
- Includes update to prop types in `organizations/model`.
- Towards #102.

Prop types update - org/containers

---

package-lock.json
package.json
src/lib/social-icons.js
src/modules/common/components/external-links-editor.jsx
src/modules/common/components/social-links-editor.jsx
src/modules/organizations/components/edit-details.jsx
src/modules/organizations/containers/details-form-container.jsx
src/modules/organizations/containers/links-container.jsx

Closes #108.
Based on PFE [external links editor](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/external-links-editor.jsx) and [social links editor](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/social-links-editor.jsx).
Staged - https://urls-editors.lab-preview.zooniverse.org/
Replaces #125 - due to issues with new social links as detailed in PR noted, this PR reflects a select for new social links; I think preferable.
Will improve styling with #122, address Cancel button issue in separate PR.

add external and social urls UI - the sequel

---

src/modules/organizations/containers/projects-container.jsx

- Adds a conditional check for projects affiliated with an organization. If no projects, return nothing and do not run `getLinkedProjects`.
- Fixes #131. 
- [Staged here](https://no-projects-error.lab-preview.zooniverse.org/).
- No spec file currently made for `ProjectsContainer`, so didn't create one just for this simple check - happy to undertake testing projects container if desired :)

Add existential check for org projects

---

src/modules/organizations/components/edit-details.jsx
test/modules/organizations/components/edit-details-test.js
test/modules/organizations/test-data.js

- Formats the display of an organization's `listed_at` date for better readability.
- Includes check on boolean property `props.organization.listed` before formatting the `listed_at` date
- `props.organization.listed` is also used in the ternary for conditionally rendering either the new listedAtDate or "N/A" according to an organization's `listed` status.
- Adds unit tests for presence of a formatted date when `props.organization.listed` is true, and renders "N/A" when false.
- [Staged here](https://listed-at-date-format.lab-preview.zooniverse.org/organizations/2).

Format org listed_at date

---

src/modules/common/components/external-links-editor.jsx
src/modules/common/components/social-links-editor.jsx
src/modules/organizations/components/about-page.jsx
src/modules/organizations/components/organization-add-project.jsx
src/modules/organizations/containers/collaborator-creator-container.jsx
src/modules/organizations/containers/details-form-container.jsx
src/modules/organizations/containers/links-container.jsx
src/styles/components/edit-details.styl
src/styles/components/image-selector.styl
src/styles/global/form.styl

I think there were three things related to form labels:
a. unrelated to the PR, but from long ago, the class `form__labels` was being used when it wasn't an actual form label, but to make a sub-section heading styled differently, or specifically in all caps and small
b. per design input, we decided these sub-section headings shouldn't be in all-caps or smaller, but should be styled what turned out to be as they would be by default
c. per design input, these sub-section headings should have a little extra margin
point c I think is overcomplicating the PR, and while we should certainly revisit, I think might be best to punt on for now

remove form label styling

---

src/modules/common/components/external-links-editor.jsx
src/modules/common/components/social-links-editor.jsx
src/modules/organizations/components/about-page.jsx
src/modules/organizations/components/edit-details.jsx
src/modules/organizations/components/organization-add-project.jsx
src/modules/organizations/containers/details-form-container.jsx
src/modules/organizations/containers/links-container.jsx
src/styles/components/edit-details.styl
src/styles/components/image-selector.styl
src/styles/global/buttons.styl
src/styles/global/form.styl

- Towards #122.
- Makes text input labels uniform in style - uses "Name" on Edit Details page as desired style.
- Text size increased:
- Help text size beneath text inputs increased
- Removed `font-size` on `form_label` to increase font size
- Delete button size reduced.
- Adds more space added divider lines.
- Space under text input labels is consistent.
- RFC: use of custom components, eg `DisplayNameSlugEditor` and `MarkdownEditor`, along with HTML inputs made it difficult for me to elegantly target the elements - current solution (below) attempts to stay within BEM conventions, but suggestions on alternative approaches are welcome.
```javascript
&__label
input.slug-editor__form-input
margin-top: 1em
&--top-margin
margin-top: 1em
```
- About page text input label has same style as Edit …

Initial design changes

---

src/modules/organizations/components/categories-editor.jsx
src/modules/organizations/components/edit-details.jsx
src/modules/organizations/containers/categories-container.jsx

Closes #90
Adds input for categories, drag-reorderable
[See PFE Issue 2970](https://github.com/zooniverse/Panoptes-Front-End/issues/2970)
Staged - https://categories.lab-preview.zooniverse.org/

add categories input to organization lab edit section

---

src/modules/organizations/components/edit-details.jsx
test/modules/organizations/components/edit-details-test.js

- Updates the UI to only show the "Listed At" field for orgs where `listed={true}`.
- For orgs where `listed={true}`, the formatted `Listed At` date still renders the same as it did previously.
- Previously, the UI displayed 'N/A' for orgs where `listed={false}` (see screen shot below).
- [Staged here](https://conditional-render-listed-at.lab-preview.zooniverse.org/).
Previous display for not listed org:
New display for not listed org:

Conditionally render the Listed At field.

---

src/modules/common/components/external-links-editor.jsx

Staged: https://external-link-xss-fix.lab-preview.zooniverse.org/
See https://github.com/zooniverse/Panoptes-Front-End/pull/5140.
Make both text inputs required.
Use `input[type=url]` for URLs and add simple pattern matching for http[s]:// URLs.
Add some string validation on change for both inputs.

Add simple URL checks to the external link editor

---

package-lock.json
package.json

Updates ZRC to latest and runs npm audit fix again. The automated fix doesn't update installs via github. Everything seems to work, but there are a few tests broken so I'm not 100% sure. These tests are broken on master so I don't think the updates are related.

Update ZRC and most recent audit fix

---

src/modules/organizations/containers/details-form-container.jsx
src/modules/organizations/containers/organizations-list-container.jsx
src/modules/organizations/containers/projects-container.jsx

Closes #181.
https://new-org-issues.lab-preview.zooniverse.org/
- fixes issue in Edit section for `null` introduction or announcement
- fixes issue in Projects section for empty array response for linked projects
To reproduce issues create a new org, check Edit section (which it'll default to on creation) and Projects section.

Fixes for org with null props, empty linked projects

---

bin/upload.js
package.json

Move the S3 upload config into its own script.
Set Cache-Control headers:
- 60s for index.html.
- 1 week for other static assets.

Set Cache-Control headers

---

package.json

`webpack -p` adds `--define process.env.NODE_ENV="'production'"`, which forces staging builds to use the production API.
Closes #199.

Remove the -p flag from builds

---

.github/pull_request_template.md
.travis.yml
README.md

Staged at https://pr-223.lab-preview.zooniverse.org/ (though no changes on actual site).
Changes made:
- updates README noting `master` merge automatically builds and deploys to production
- updates README noting PRs' staging build and variable deployment
- creates PR template including note on variable staging deployment
- updates `.travis.yml` to fix build error (i.e. [Build 50](https://travis-ci.com/github/zooniverse/pfe-lab/builds/212259980))
Largely documentation update per #214.

Update README, PR template, .travis.yml

---

.github/workflows/deploy_branch.yml

Don't use the `_build-production` npm command on staging

Use staging npm command in staging deploy

---

.github/workflows/run_tests.yml
.travis.yml
Dockerfile
package.json

Updates to Node 14 and removes Travis in favor of Github Actions for running tests.

Upgrade to Node 14. Remove Travis for GA

---

.github/workflows/deploy_branch.yml
.github/workflows/deploy_staging.yml
README.md
package.json

Adds the master branch deployment that we missed and explicitly set node env for staging.

Add GA for master branch deployment

---

.github/workflows/deploy_branch.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
.github/workflows/run_tests.yml
.mocharc.js
package-lock.json
package.json
test/mocha.opts

Staging branch URL: https://pr-252.lab-preview.zooniverse.org/
Closes https://github.com/zooniverse/how-to-zooniverse/issues/137.
- Use [`npm ci`](https://docs.npmjs.com/cli/v7/commands/npm-ci) for builds.
- Re-use the npm cache across installs, when `package-lock.json` is unchanged.
- Add `$HEAD_COMMIT` to the deployment environment on the main branch. It's used to add the latest commit hash to the page HTML.
- Publish `/commit_id.txt` on deploy.
- Run `npm audit fix` to fix some outdated dependencies.
- Upgrade `mocha` to 8.4 to fix a security warning for old dependencies. Replace `mocha.opts` with `.mocharc.js`.
- Use `https:` to install Zooniverse-React-Components. `npm ci` breaks with `ssh:` URLs. See https://github.com/actions/setup-node/issues/214#issuecomment-810829250
There's one …

[Security] Upgrade all the things

---

package-lock.json
package.json

Staging branch URL: https://pr-258.lab-preview.zooniverse.org/
- updates `markdownz` to v7.8.1

[Security] Update markdownz to 7.8.1

---

package-lock.json
package.json
webpack.config.js

Upgrade `webpack-dev-server`, `webpack-cli` and `webpack-dashboard` to the latest versions, which should fix a bunch of dependabot security alerts for outdated dependencies.
Staging branch URL: https://pr-271.lab-preview.zooniverse.org/

Upgrade webpack-dev-server to v4

---

package-lock.json
package.json

- updates `zooniverse-react-components` to v0.9.6, fixes issue with previous version of ZRC stuck at v0.9.0

Update zooniverse-react-components to v0.9.6

---

package-lock.json
package.json
webpack.config.js
webpack.production.config.js

Remove `image-webpack-loader` in favour of Webpack 5 asset modules.
Staging branch URL: https://pr-400.lab-preview.zooniverse.org/
Closes https://github.com/zooniverse/pfe-lab/security/dependabot/61.

Remove image-webpack-loader

---

.github/workflows/deploy_branch.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml
.github/workflows/run_tests.yml
Dockerfile
package-lock.json
package.json
test/utils/dom.js

- update `package.json`.
- update Dockerfile.
- update GitHub workflows.
Node 16 entered maintenance mode in October 2022 and support ends in September 2023. 
Staging branch URL: https://pr-401.lab-preview.zooniverse.org/

Build with Node 18 (lts/hydrogen)

---

src/styles/components/landing.styl
webpack.config.js
webpack.production.config.js

Attempt to fix issue causing JS asset loading to 404.
Fixes #250
Reverts #225
Staging branch URL: https://pr-684.lab-preview.zooniverse.org/
- Does an organization editing page (e.g., https://lab.zooniverse.org/organizations/85) load correctly?

Fix JS Asset Loading
