zooniverse/pfe-lab

src/index.tpl.html
src/modules/common/components/footer.jsx
src/modules/common/components/layout.jsx
src/styles/components/footer.styl

initial add of PFE footer, open items (including adding "Build an Organization" nav item?) noted in issue #13

add footer

---

package.json
server.js
webpack.config.js
yarn.lock

Added webpack dashboard

---

package.json
yarn.lock

This adds zooniverse/Zooniverse-React-Components as a dependency.

Added zoo react components dependency

---

src/modules/common/components/landing.jsx
src/modules/common/components/site-footer.jsx
src/modules/common/components/site-nav.jsx
src/styles/components/site-nav.styl

- Zooniverse logo on the header
- Zooniverse logotype on the landing page
- Zooniverse logotype on the footer

Insert Zooniverse Logos in Placeholders

---

package.json
yarn.lock

Updates to 0.2.0 of the zooniverse-react-components dependency.

bumped component dep version

---

src/modules/organizations/containers/organization-container.jsx
yarn.lock

add background to organization request include

add background to organization request include

---

package.json
webpack.config.js
webpack.production.config.js

Closes #9.
Related static files:

update staging and deploy scripts

---

src/constants/config.js
src/modules/common/components/site-nav.jsx

Closes #71.
Implemented with the ZooLogo in the nav for starters, but think could be used elsewhere.

add zooniverse urls per env to config

---

src/modules/organizations/components/organization-layout.jsx
src/modules/organizations/index.jsx
src/styles/components/organization-layout.styl
src/styles/global/nav-list.styl

Fixes part of #69.
Basic changes to mimic left-nav of PFE Project Builder.
Minor edits to path and routes to get activeClassName working on Edit tab.

Add left-nav styling

---

src/modules/organizations/components/about-page.jsx
src/modules/organizations/components/edit-collaborators.jsx
src/modules/organizations/components/edit-details.jsx
src/modules/organizations/containers/projects-container.jsx
src/styles/components/organization-layout.styl

Fixes part of #69.
Adds a uniform basic section header styling for each of the pages available from the nav bar.

Add section headers for organization pages.

---

src/modules/organizations/components/edit-collaborators.jsx
src/modules/organizations/containers/collaborator-creator-container.jsx
src/styles/components/organization-collaborators.styl

Fixes part of #69. 
Add basic styling to org-collaborators page.

Org-collaborators page styling

---

src/modules/organizations/components/edit-collaborators.jsx
src/modules/organizations/components/organization-projects-list.jsx
src/modules/organizations/containers/collaborator-creator-container.jsx
src/modules/organizations/containers/collaborators-container.jsx
src/modules/organizations/containers/projects-container.jsx
src/styles/components/organization-collaborators.styl

add display_name to collaborators list

---

package-lock.json
src/modules/organizations/components/organization-projects-list.jsx
src/modules/organizations/containers/collaborators-container.jsx
src/modules/organizations/containers/projects-container.jsx

Towards #45.
- Updates zooniverse-react-components dependency to 0.3.0
- Adds paginator to organization projects
- Adds paginator to organization collaborators

Add pagination to Organization projects and collaborators pages.

---

src/modules/organizations/containers/projects-container.jsx

- Adds instruction text for OrganizationAddProject component.

Add instruction text to 'Add a project'.

---

src/modules/organizations/containers/collaborators-container.jsx
src/modules/organizations/containers/projects-container.jsx

- Adds ability to display multiple pages via Paginator component
- Catch up on some linting warnings/errors (propTypes, defaultProps)
- Builds on work done in [pfe-lab#81](https://github.com/zooniverse/pfe-lab/pull/81)
- Resolves #45 
- `page-size` is set to default

Paginator for Organization pages

---

src/modules/organizations/components/list-group.jsx
src/modules/organizations/components/organizations-list.jsx

edit view org and help button urls on orgs list

edit view org and help button urls on orgs list

---

src/modules/organizations/containers/edit-details-container.jsx

edit avatar and background fetches
closes #86

edit avatar and background fetches

---

package-lock.json
package.json
src/modules/common/containers/admin-container.jsx
test/modules/common/admin-container-test.js

- This PR creates tests for the AdminContainer component that was added as part of the integration of the ZRC footer (PR #101).
- Assertions and general testing format follow implementation in `edu-api-front-end`'s [AdminContainer spec](https://github.com/zooniverse/edu-api-front-end/blob/8fb96c2f0cfe008de667068cd81174010b370421/src/containers/layout/AdminContainer.spec.jsx).
- Package dependency updates:
- `sinon`
- `mock-local-storage`
- `dispatch` prop is given a `defaultProps` value of a function that returns an empty object (`() => {}`).
- Export statement re-added to AdminContainer class to enable testing without connecting to redux store.
- Towards #102.
- Staged [here](https://admin-container-tests.lab-preview.zooniverse.org/).
- For a user, everything looks the same.
- App layout …

Admin container tests

---

src/modules/organizations/containers/projects-container.jsx

fixes issue when going from one org to another, org projects wouldn't properly update or would hit error

reset org projects on container unmount

---

src/modules/organizations/containers/collaborators-container.jsx

- Update explanatory text for organization collaborators to include their ability to remove projects from an organization.
- Towards #109.

Update collaborator explanatory text

---

src/modules/common/components/resources-list.jsx
src/modules/organizations/components/about-page.jsx
src/modules/organizations/components/edit-collaborators.jsx
src/modules/organizations/components/edit-details.jsx
src/modules/organizations/components/organization-add-project.jsx
src/modules/organizations/components/organization-projects-list.jsx
src/modules/organizations/containers/projects-container.jsx
src/styles/components/organization-layout.styl
src/styles/components/resources-list.styl

- Instructions/explanatory text for an org's projects (items relating to projects on issue #109) are now displayed beneath the 2 section headers (AFFILIATED PROJECTS and ADD PROJECTS TO THIS ORGANIZATION)
- I think having each of the sentences as separate lines (basically more like bullet points) makes them easier to read, as opposed to a series of sentences in one solid block of text. Would love design input from others about this, but I worked according to this principle.
- Created a class, `organization-section-instructions`, to add some spacing between each of the lines of text.
- Created `formatInstructions()` to add HTML elements with the `organization-section-instructions` class, rather than having a bunch of `<div className="organization-section-instructions">` elements in the …

Update project instructions

---

src/modules/organizations/containers/collaborators-container.jsx

use getMeta

---

src/modules/organizations/components/about-page.jsx
src/styles/global/buttons.styl
src/styles/global/form.styl
src/styles/global/typography.styl

Towards #122.
- increase font-size to same as PFE Project Builder
- edit form label styling
- edit organization about page styling

edit font-size, form label and about page

---

src/modules/organizations/containers/categories-container.jsx
src/modules/organizations/containers/links-container.jsx
src/modules/organizations/containers/organization-container.jsx

Fix links and categories cancel

---

src/modules/organizations/containers/details-form-container.jsx
src/modules/organizations/containers/organization-container.jsx

Closes #127. 
- Refactor details form to use state (more).
- Only submit changed fields.

refactor details form

---

src/modules/organizations/containers/details-form-container.jsx

add announcement input

---

package-lock.json
package.json
src/modules/organizations/containers/about-container.jsx
src/modules/organizations/containers/details-form-container.jsx

Adds `dompurify` dependency and sanitizes all of the text inputs. This is just preventative. There aren't any known exploits that have happened with the organization resource.

Sanitize the text inputs

---

src/modules/common/components/external-links-editor.jsx

Refactor external link key so it's not included in saved organization resource url attribute.

Refactor external link key

---

package-lock.json
package.json
src/modules/common/components/landing.jsx

Closes #159.
On landing, edits project building help link from broken link to https://www.zooniverse.org/help.

Update help link

---

package-lock.json
package.json
src/store.js

Remove redux-logger dependency

---

src/modules/common/components/landing.jsx

Update landing organization content

---

package-lock.json
package.json

- updates Zooniverse-React-Components to v0.9.1
- runs `npm audit fix`

Update Zooniverse-React-Components, npm audit fix

---

test/modules/organizations/components/edit-details-test.js
test/modules/organizations/components/organizations-list-test.js
test/modules/organizations/containers/organization-container-test.js

Bare minimum (other than deleting) to fix broken tests. All tests now pass, 1 pending.

Fix broken tests

---

src/modules/organizations/containers/edit-details-container.jsx

This adds the required new header for this to work with Azure.

Add MS header to media PUT request

---

webpack.config.js
webpack.production.config.js

Staging branch URL: https://pr-225.lab-preview.zooniverse.org/
Fixes the background image URL loading from CSS on Azure.

Remove public path from webpack configs

---

.github/workflows/main.yml

Include NODE_ENV env var in GH action

---

.github/workflows/main.yml
package.json

Build production npm script

---

.github/workflows/main.yml

Add cache headers to uploads, upload index.html separately

---

.github/workflows/deploy_branch.yml
.github/workflows/deploy_production.yml

Adds Deploy Staging Branch github action

---

.github/workflows/deploy_production.yml

Add missing field for runtime

---

package-lock.json
package.json

Staging branch URL: https://pr-251.lab-preview.zooniverse.org/
(^ included in Doorkeeper )
Describe your changes:
- remove `s3-batch-upload` dependency, no longer used with Azure hosting and GHA CI/CD

Remove s3-batch-upload dependency

---

package-lock.json
package.json

Staging branch URL: https://pr-267.lab-preview.zooniverse.org/
- update Zooniverse-React-Components to v0.9.4
- run `npm audit`

Update ZRC, npm audit

---

.github/workflows/deploy_branch.yml
.github/workflows/deploy_production.yml
.github/workflows/deploy_staging.yml

Staging branch URL: https://pr-268.lab-preview.zooniverse.org/
Fixes #263. 
- refactors GitHub Actions workflows to use shared zooniverse workflows - https://github.com/zooniverse/ci-cd/tree/main/.github/workflows
~@zwolf - feel free to, or let me know and I'll, convert this from Draft to Ready for Review and we can see what happens.~
never mind! ^ :facepalm workflows will need to merged

Refactor for zooniverse shared workflows

---

src/index.tpl.html

Staging branch URL: https://pr-681.lab-preview.zooniverse.org/

Security: remove polyfill.io
